### ISSUE TITLE
Isoparser issues

### ISSUE THREAD

**Issue by xTriixrx** [templars-community/TempleOS-Archive-Extractor#1]
I am trying to use this repository as a way to extract HolyC files I have written in my VM instance of Temple OS. To test this, I am using the base .ISO img for Temple OS which I used to create the VM. I attempted to run the following:

python extract_templeos.py TempleOS.ISO ThirdTemple/ '2020-09-02 21:43:28'

and I receive the following error:

Traceback (most recent call last):
  File "extract_templeos.py", line 16, in <module>
    iso = isoparser.parse(ISO_FILE)
  File "isoparser/isoparser/__init__.py", line 23, in parse
    return iso.ISO(src)
  File "isoparser/isoparser/iso.py", line 31, in __init__
    root_record = self.root.current_directory
AttributeError: 'NoneType' object has no attribute 'current_directory'

I have been digging through both the code in this repo and the code in the isoparser and have not been able to find a solution. As you the maintainer are more familiar with this code, do you have any guidance on how I would be able to get this working / extract source ASCII files from the Temple OS VM environment onto a my host machine (Mac OS X).

**Comment by xTriixrx** [comment]
I have figured out a way around using this repository to those who stumble across this. Simply using the following commands I was able to rebuild my VMDK into an ISO and extract the files I wanted from the ISO:

qemu-img convert -f vmdk vd.vmdk vd.raw
dd if=vd.raw of=thirdTemple.iso

This requires having qemu installed which should not be hard to get, Mac OS users can use homebrew to install this. Once the iso is created there are ways around into digging into the ISO, using Mac OS you can use Disk Utility to open a Disk Image and copy out the HC.Z files that you would like to extract. .Z files will need to be decompressed using the TOSZ executable which Terry (thankfully) had provided. I suggest extracting the .CPP file and recompiling the binary on your host machine:

gcc TOSZ.CPP -o TOSZ

Once TOSZ has been rebuilt you can finally see your HolyC file:

./TOSZ Hello.HC.Z

**Comment by minexew** [comment]
I can only guess that your ISO was actually in RedSea format. Therefore isoparser had no idea how to handle it. You might have more luck with the more recent extraction code here: https://github.com/cia-foundation/TempleOS/tree/master

Do keep in mind, though, that it relies on FUSE, and support on anything non-Linux will probably be extremely spotty.
